version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    ports:
      - '5431:5432' # Mapeia a porta do container para a 5431 no host
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  prisma:
    image: node:20
    container_name: prisma_service
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma generate && npx prisma db push"
    environment:
      DATABASE_URL: 'postgresql://myuser:mypassword@postgres:5432/mydatabase'
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  app_network:
